### ISSUE TITLE
@Sections= and @Rank= logic unclear

### ISSUE THREAD

**Issue by polezhaevdmi** [marcapelini/RTProfileSelector#4] opened 2017-06-05 20:16 UTC
OS: Windows 7 x64
The rules file is simple and attached below.
The "Canon EF 24-70mm F2.8L USM.pp3" profile does not apply (no log events / no lens-special parameters copied), when the "@Sections=" line is active.
If the "@Sections=" is commented out, the lens-specific file copies fine.
Tried to remove the _Vignetting Correction_ and double-quote it. In vain.
Seems, something wrong in the "@Sections=" line parcer.

Almost the same with the "@Rank=" line: if it active - no data copied.

The desired behaviour: the listed sections from "Canon EF 24-70mm F2.8L USM.pp3" file should override (or added) the sections from "Canon EOS 5D Mark III.pp3" file (as it has Rank=0 by default).

> ["Canon EOS 5D Mark III.pp3"]
> Camera Model Name=Canon EOS 5D Mark III
> 
> ["Canon EF 24-70mm F2.8L USM.pp3"]
> @Rank=10
> @Sections=LensProfile,CACorrection,Vignetting Correction,Sharpening,Defringing
> Lens ID=Canon EF 24-70mm f/2.8L

**Comment by marcapelini** [comment] 2017-06-07 00:12
Thanks for reporting the problem! I don't think I'll have the time to work on it in the next couple of weeks, but will take a look at it as soon as possible.  ~~Without looking at the code, it strikes me that all string comparisons are case sensitive, so your "@rank" (as opposed to "@Rank") might not work anyway.~~  Never mind previous comment, just realised github must be doing some automatic formatting with the uppercase after the @ sign...

Also I don't think I have used quotes in the section names of any of my own rules, but you don't seem to have any issue with them, do you? I mean, I'm a bit unsure that ["Canon EF 24-70mm F2.8L USM.pp3"] (instead of [Canon EF 24-70mm F2.8L USM.pp3] without quotes) should work at all...

**Comment by polezhaevdmi** [comment] 2017-06-09 19:38
> just realised github must be doing some automatic formatting

Yes, I also spent some time in playing with GitHub 'artificial intelligence', while creating the initial text. Seems I born to be a QA-Engineer: issues are like of being found by me. :)

> will take a look at it as soon as possible

OK, as the workaround might be simple: prepare separate templates and make a choice on "Body+Lens" basis. This is enough for beginning.

> I don't think I have used quotes in the section names of any of my own rules, but you don't seem to have any issue with them, do you?

Seems yes, quotes have no effect on the result.  I will play more with the actual version and report here. May be the workaround is not so far...

**Comment by polezhaevdmi** [comment] 2017-06-11 17:36
Tried to play with simplified names. 

[**b.pp3**]
Camera Model Name=Canon EOS 5D Mark III

[**l1.pp3**]
;@Rank=10
@Sections=LensProfile,CACorrection,Vignetting Correction,Sharpening,Defringing
Lens ID=Canon EF 24-70mm f/2.8L
Camera Model Name=Canon EOS 5D Mark III

In vain.

Error copying source -> destination profile:
"C:\\Program Files\\RawTherapee\\profiles"\b.pp3 -> **D:\PHOTO\IMG_2749.CR2.pp3**

**Comment by polezhaevdmi** [comment] 2017-06-11 19:15
Marcos, the issue does not affect @Sections syntax I found a letter difference in the file names, that is my fault. The @Rank still does not work as desired, but the rule configuration below good enough as workaround. It produces the desired result even without rank set. The log has one record about body profile copy, however, I see the added lens-specific sections in the output file (sure, the body file has no lens sections set).

> [Canon_EOS_5D_Mark_III.pp3]
> Camera Model Name=Canon EOS 5D Mark III
> 
> [Canon_EF_24_70mm_f_2_8L_USM.pp3]
> ;@Rank=10
> @Sections=LensProfile,CACorrection,Vignetting Correction,Sharpening,Defringing
> Lens ID=Canon EF 24-70mm f/2.8L
> Camera Model Name=Canon EOS 5D Mark III
> 
> [Canon_EF_8_15mm_F_4L_Fisheye_USM.pp3]
> ;@Rank=10
> @Sections=LensProfile,CACorrection,Vignetting Correction,Sharpening,Defringing
> Lens ID=Canon EF 8-15mm f/4L Fisheye USM
> Camera Model Name=Canon EOS 5D Mark III
>

**Comment by marcapelini** [comment] 2021-02-05 15:48
I cannot reproduce this problem. I'll make a suggestion (if you're still using RTPS after almost 4 years of this issue being open...): try to run your rules through the new code that I pushed yesterday (there should be no changes in behaviour, just more information to find out the cause of rules's real or apparent misbehaviour) . The last couple of commits (see my comment in issue #3) bring improvements to logging and profile debugging, so it should be much easier now to figure out which profiles & rules are actually being applied, in which order, and where each key in the final generated profile came from.  I'm closing this issue for now.

**Closed as completed by marcapelini** 2021-02-05 15:48 UTC

**Comment by polezhaevdmi** [comment] 2021-02-05 21:21
A lot of thanks, Marcos, I will try again, indeed.

**Comment by marcapelini** [comment] 2021-02-05 23:03
> A lot of thanks, Marcos, I will try again, indeed.

By the way, if you're still on Windows, and you're not able to compile the source code yourself, you may have to wait until I publish a new release with a compiled Windows binary.  I can compile it in a VM but I'm not able test it any more, since I no longer have a Windows environment with RawTherapee installed.  Moved on to a Kubuntu-only photo workflow...

**Comment by polezhaevdmi** [comment] 2021-02-07 20:38
Not a problem, Marcos, despite my code development skills are dummy, this was enough to deploy the Visual Studio and build the executable module. At least, I see, RTSP puts more into log, even being run without parameters. :) I'll continue with RTSP profiles and RT 5.8, as my summer photo not processed yet.
P.S.> Actual RT (version 5.8, Win10x64) appeared not able to invoke RTSP at all, now I'm investigating, what coders might broke inside it...

**Comment by marcapelini** [comment] 2021-02-08 21:02
> P.S.> Actual RT (version 5.8, Win10x64) appeared not able to invoke RTSP at all, now I'm investigating, what coders might broke inside it...

I just installed the latest RT 5.8 in a Windows 7 virtual machine, set up RT to call RTPS as per my instructions on the wiki section, and everything was fine (application called, log and debug files created):
![Screenshot_20210208_175524](https://user-images.githubusercontent.com/1328887/107280558-421eea80-6a37-11eb-8261-1bd98524d944.png)

I used a Windows RTPS binary compiled with Visual Studio 2019, which I attached to the [Release 1.0.5](https://github.com/marcapelini/RTProfileSelector/releases/tag/v1.0.5).
